version: '2'
services:
  proxy:
    build:
      context: ./envoy
      args:
        - "file-flush-interval-msec 60000"
      dockerfile: Dockerfile.proxy
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy.yaml
      - ./lib-body-logging/target/wasm32-unknown-unknown/release/body_logging.wasm:/etc/body_logging.wasm
      - ./lib-prime-auth/target/wasm32-unknown-unknown/release/prime_auth.wasm:/etc/prime_auth.wasm
      - ./modsecurity-wasm-filter/wasmplugin/modsec.wasm:/etc/modsec.wasm
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
    ports:
      - "18000:80"
      - "18001:8001"

  web_service:
    image: hashicorp/http-echo
    command:
      - '-text="Welcome to WASM land"'
    networks:
      envoymesh:
        aliases:
          - web_service
    expose:
      - "5678"
    ports:
      - "18080:5678"

networks:
  envoymesh: {}
